# Form implementation generated from reading ui file 'simulator_ui.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def __init__(self, rack_group_id = 1, left=0, top=0, width=360, height=320):
        super().__init__()
        self.rack_group_id = rack_group_id
        self.left = left
        self.top = top
        self.width = width
        self.height = height
        self.rackGroupList = []

    def create_layout_rack_group(self, number):
        rackGroup = MyGroupBox(rack_group_id=number+1, left=self.left, top=self.top+(self.height+20)*number, width=self.width, height=self.height)
        self.rackGroupList.append(rackGroup)
        return rackGroup.rackGroup

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(752, 693)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")

        self.vGroupBoxLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)

        # rack group
#        for index in range(21):
#            self.rackGroup = MyGroupBox(parent=self.scrollAreaWidgetContents, rack_group_id=index, left=self.left, top=self.top+(self.height+10)*(index - 1), width=self.width, height=self.height)
#            self.rackGroupList.append(self.rackGroup)

        
        # Scroll Area
        self.scrollArea = QtWidgets.QScrollArea()
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setFixedWidth(420)

        for i in range(21):
            self.vGroupBoxLayout.addWidget(self.create_layout_rack_group(i))

        self.vBoxLayout = QtWidgets.QVBoxLayout()
        self.vBoxLayout.addWidget(self.scrollArea)


        self.centralwidget.setLayout(self.vBoxLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 752, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate

        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        for i in range(21):
            self.rackGroupList[i].retranslateUi()
#        self.rackGroup2.retranslateUi()
#        self.rackGroup3.retranslateUi()
#        self.rackGroup4.retranslateUi()
#        self.rackGroup5.retranslateUi()
#        self.rackGroup6.retranslateUi()


class MyGroupBox:
    def __init__(self, rack_group_id, left, top, width, height):
        super().__init__()
        self.rack_group_id = rack_group_id
        self.rackGroup = QtWidgets.QGroupBox()
        self.rackGroup.setGeometry(QtCore.QRect(left, top, width, height))
        self.rackGroup.setObjectName("rackGroup")
        self.widget = QtWidgets.QWidget(parent=self.rackGroup)
        self.widget.setGeometry(QtCore.QRect(20, 20, 336, 261))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.rackGroup)
        self.verticalLayout.setContentsMargins(30, 10, 30, 10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_15 = QtWidgets.QLabel(parent=self.widget)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_7.addWidget(self.label_15)
        self.rackIDNumbersComboBox = QtWidgets.QComboBox(parent=self.widget)
        self.rackIDNumbersComboBox.setObjectName("rackIDNumbersComboBox")
        self.rackIDNumbersComboBox.addItem("")
        self.rackIDNumbersComboBox.addItem("")
        self.rackIDNumbersComboBox.addItem("")
        self.rackIDNumbersComboBox.addItem("")
        self.rackIDNumbersComboBox.addItem("")
        self.rackIDNumbersComboBox.addItem("")
        self.horizontalLayout_7.addWidget(self.rackIDNumbersComboBox)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_13 = QtWidgets.QLabel(parent=self.widget)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_8.addWidget(self.label_13)
        self.OperationsComboBox = QtWidgets.QComboBox(parent=self.widget)
        self.OperationsComboBox.setObjectName("OperationsComboBox")
        self.OperationsComboBox.addItem("")
        self.OperationsComboBox.addItem("")
        self.OperationsComboBox.addItem("")
        self.OperationsComboBox.addItem("")
        self.horizontalLayout_8.addWidget(self.OperationsComboBox)
        self.runButton = QtWidgets.QPushButton(parent=self.widget)
        self.runButton.setObjectName("runButton")
        self.horizontalLayout_8.addWidget(self.runButton)
        self.stopButton = QtWidgets.QPushButton(parent=self.widget)
        self.stopButton.setObjectName("stopButton")
        self.horizontalLayout_8.addWidget(self.stopButton)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.ObstructCheckBox = QtWidgets.QCheckBox(parent=self.widget)
        self.ObstructCheckBox.setObjectName("ObstructCheckBox")
        self.horizontalLayout_17.addWidget(self.ObstructCheckBox)
        self.OverloadMotorCheckBox = QtWidgets.QCheckBox(parent=self.widget)
        self.OverloadMotorCheckBox.setObjectName("OverloadMotorCheckBox")
        self.horizontalLayout_17.addWidget(self.OverloadMotorCheckBox)
        self.SkewCheckBox = QtWidgets.QCheckBox(parent=self.widget)
        self.SkewCheckBox.setObjectName("SkewCheckBox")
        self.horizontalLayout_17.addWidget(self.SkewCheckBox)
        self.simulatorErrorButton = QtWidgets.QPushButton(parent=self.widget)
        self.simulatorErrorButton.setObjectName("simulatorErrorButton")
        self.horizontalLayout_17.addWidget(self.simulatorErrorButton)
        self.verticalLayout.addLayout(self.horizontalLayout_17)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_9 = QtWidgets.QLabel(parent=self.widget)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout.addWidget(self.label_9)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtWidgets.QLabel(parent=self.widget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 3, 1, 1)
        self.label = QtWidgets.QLabel(parent=self.widget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.temperature = QtWidgets.QLCDNumber(parent=self.widget)
        self.temperature.setStyleSheet("QLCDNumber{\n"
"  background-color: rgb(0, 0, 0);\n"
"  color: rgb(255, 255, 255);\n"
"}")
        self.temperature.setSmallDecimalPoint(False)
        self.temperature.setSegmentStyle(QtWidgets.QLCDNumber.SegmentStyle.Filled)
        self.temperature.setObjectName("temperature")
        self.gridLayout.addWidget(self.temperature, 1, 0, 1, 1)
        self.humidity = QtWidgets.QLCDNumber(parent=self.widget)
        self.humidity.setStyleSheet("QLCDNumber{\n"
"  background-color: rgb(0, 0, 0);\n"
"  color: rgb(255, 255, 255);\n"
"}")
        self.humidity.setObjectName("humidity")
        self.gridLayout.addWidget(self.humidity, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.widget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=self.widget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 2, 1, 1)
        self.weight = QtWidgets.QLCDNumber(parent=self.widget)
        self.weight.setStyleSheet("QLCDNumber{\n"
"  background-color: rgb(0, 0, 0);\n"
"  color: rgb(255, 255, 255);\n"
"}")
        self.weight.setObjectName("weight")
        self.gridLayout.addWidget(self.weight, 1, 2, 1, 1)
        self.smoke = QtWidgets.QLCDNumber(parent=self.widget)
        self.smoke.setStyleSheet("QLCDNumber{\n"
"  background-color: rgb(0, 0, 0);\n"
"  color: rgb(255, 255, 255);\n"
"}")
        self.smoke.setObjectName("smoke")
        self.gridLayout.addWidget(self.smoke, 1, 3, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_10 = QtWidgets.QLabel(parent=self.widget)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_4.addWidget(self.label_10)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_6 = QtWidgets.QLabel(parent=self.widget)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(parent=self.widget)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 0, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(parent=self.widget)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 0, 3, 1, 1)
        self.movementSpeed = QtWidgets.QLCDNumber(parent=self.widget)
        self.movementSpeed.setStyleSheet("QLCDNumber{\n"
"  background-color: rgb(0, 0, 0);\n"
"  color: rgb(255, 255, 255);\n"
"}")
        self.movementSpeed.setObjectName("movementSpeed")
        self.gridLayout_2.addWidget(self.movementSpeed, 1, 0, 1, 1)
        self.displacement = QtWidgets.QLCDNumber(parent=self.widget)
        self.displacement.setStyleSheet("QLCDNumber{\n"
"  background-color: rgb(0, 0, 0);\n"
"  color: rgb(255, 255, 255);\n"
"}")
        self.displacement.setObjectName("displacement")
        self.gridLayout_2.addWidget(self.displacement, 1, 1, 1, 1)
        self.isHardLock = QtWidgets.QLCDNumber(parent=self.widget)
        self.isHardLock.setStyleSheet("QLCDNumber{\n"
"  background-color: rgb(0, 0, 0);\n"
"  color: rgb(255, 255, 255);\n"
"}")
        self.isHardLock.setObjectName("isHardLock")
        self.gridLayout_2.addWidget(self.isHardLock, 1, 2, 1, 1)
        self.isEndpoint = QtWidgets.QLCDNumber(parent=self.widget)
        self.isEndpoint.setStyleSheet("QLCDNumber{\n"
"  background-color: rgb(0, 0, 0);\n"
"  color: rgb(255, 255, 255);\n"
"}")
        self.isEndpoint.setObjectName("isEndpoint")
        self.gridLayout_2.addWidget(self.isEndpoint, 1, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(parent=self.widget)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout_2)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_11 = QtWidgets.QLabel(parent=self.widget)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_6.addWidget(self.label_11)
        self.rackGroupErrorLineEdit = QtWidgets.QLineEdit(parent=self.widget)
        self.rackGroupErrorLineEdit.setStyleSheet("QLineEdit{\n"
"  background-color: rgb(0, 0, 0);\n"
"  color: rgb(255, 255, 255);\n"
"}")
        self.rackGroupErrorLineEdit.setObjectName("rackGroupErrorLineEdit")
        self.horizontalLayout_6.addWidget(self.rackGroupErrorLineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_12 = QtWidgets.QLabel(parent=self.widget)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_5.addWidget(self.label_12)
        self.rackGroupStateLineEdit = QtWidgets.QLineEdit(parent=self.widget)
        self.rackGroupStateLineEdit.setStyleSheet("QLineEdit{\n"
"  background-color: rgb(0, 0, 0);\n"
"  color: rgb(255, 255, 255);\n"
"}")
        self.rackGroupStateLineEdit.setObjectName("rackGroupStateLineEdit")
        self.horizontalLayout_5.addWidget(self.rackGroupStateLineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_5)

#        self.horizontalLayout_7.addStretch(1)
#        self.horizontalLayout.addStretch(1)
#        self.horizontalLayout_17.addStretch(1)
#        self.horizontalLayout_4.addStretch(1)
#        self.horizontalLayout_5.addStretch(1)
#        self.horizontalLayout_6.addStretch(1)
#        self.horizontalLayout_8.addStretch(1)
        self.verticalLayout.addStretch(1)
        
    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.rackGroup.setTitle(_translate("MainWindow", "Group "+ str(self.rack_group_id)))
        self.runButton.setText(_translate("MainWindow", "Run"))
        self.stopButton.setText(_translate("MainWindow", "Stop"))
        self.simulatorErrorButton.setText(_translate("MainWindow", "Simulate Error"))
        self.label_15.setText(_translate("MainWindow", "Rack ID"))
        self.rackIDNumbersComboBox.setItemText(0, _translate("MainWindow", str((self.rack_group_id - 1) * 6 + 1)))
        self.rackIDNumbersComboBox.setItemText(1, _translate("MainWindow", str((self.rack_group_id - 1) * 6 + 2)))
        self.rackIDNumbersComboBox.setItemText(2, _translate("MainWindow", str((self.rack_group_id - 1) * 6 + 3)))
        self.rackIDNumbersComboBox.setItemText(3, _translate("MainWindow", str((self.rack_group_id - 1) * 6 + 4)))
        self.rackIDNumbersComboBox.setItemText(4, _translate("MainWindow", str((self.rack_group_id - 1) * 6 + 5)))
        self.rackIDNumbersComboBox.setItemText(5, _translate("MainWindow", str((self.rack_group_id - 1) * 6 + 6)))
        self.label_13.setText(_translate("MainWindow", "Operation"))
        self.OperationsComboBox.setItemText(0, _translate("MainWindow", "Open"))
        self.OperationsComboBox.setItemText(1, _translate("MainWindow", "Close"))
        self.OperationsComboBox.setItemText(2, _translate("MainWindow", "Light"))
        self.OperationsComboBox.setItemText(3, _translate("MainWindow", "Ventilate"))
        self.ObstructCheckBox.setText(_translate("MainWindow", "Obstruct"))
        self.SkewCheckBox.setText(_translate("MainWindow", "Skew"))
        self.OverloadMotorCheckBox.setText(_translate("MainWindow", "Overload motor"))
        self.label_9.setText(_translate("MainWindow", "ENV"))
        self.label_4.setText(_translate("MainWindow", "Smoke"))
        self.label.setText(_translate("MainWindow", "Temperature"))
        self.label_2.setText(_translate("MainWindow", "Humidity"))
        self.label_3.setText(_translate("MainWindow", "Weight"))
        self.label_10.setText(_translate("MainWindow", "OPR"))
        self.label_6.setText(_translate("MainWindow", "Displacement"))
        self.label_7.setText(_translate("MainWindow", "Is Hard Locked"))
        self.label_8.setText(_translate("MainWindow", "Is Endpoint"))
        self.label_5.setText(_translate("MainWindow", "Speed"))
        self.label_11.setText(_translate("MainWindow", "ERROR"))
        self.label_12.setText(_translate("MainWindow", "STATE "))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
